### ISSUE TITLE
Safari 10.1 throws Error: The provided value is non-finite

### ISSUE THREAD

**Issue by ChristiaanScheermeijer** [mozilla/vtt.js#364]
When using vtt.js in Safari it throws `Error: The provided value is non-finite` on this part `cue.line = settings.get("line", "auto");`.

I think this is an issue in the Safari VTTCue implementation, but I hope to find a workaround in this polyfill.

Below the stacktrace:

```
consumeCueSettings@http://localhost:9000/bower_components/vtt.js/lib/vtt.js:269:10
parseCue@http://localhost:9000/bower_components/vtt.js/lib/vtt.js:303:23
parse@http://localhost:9000/bower_components/vtt.js/lib/vtt.js:1268:23
```

- macOS Sierra 10.12.4 
- Safari Version 10.1 (12603.1.30.0.34)

**Comment by johnBartos** [comment]
Here's what we do in jwplayer:

````
var line = settings.get('line', 'auto');
if (line === 'auto' && defaults.line === -1) {
    // set numeric line number for Safari
    line = -1;
}
cue.line = line;
````

**Comment by aligon** [comment]
Here's how we worked around it:

```js
const oldVTTCue = global.VTTCue;

try {
    global.VTTCue = VTTCue;

    parser.parse(vtt);
    parser.flush();
} finally {
    global.VTTCue = oldVTTCue;
}
```

The VTTCue in scope is the one from vtt.js

**Comment by jsg2021** [comment]
The spec clearly allows for `'auto'` :|
https://w3c.github.io/webvtt/#webvtt-cue-line

Apple's native VTTCue is not spec compliant.

**Comment by ChristiaanScheermeijer** [comment]
Agreed, but why not solving it in the polyfill?

**Comment by ChristiaanScheermeijer** [comment]
Thanks, `cue.position` also throws this error.

**Comment by jsg2021** [comment]
I added position to my PR

**Comment by jsg2021** [comment]
Apparently the travis build failed with that change... :/ position wasn't 'auto'?

**Comment by jsg2021** [comment]
Ugh... apparently that breaks the tests. cue.position is auto by default (in chrome & ff...in safari its 50) and I'm just using the default if set... and falling back to what was there... :/

**Comment by ChristiaanScheermeijer** [comment]
Im using `cue.line !== "auto" ? cue.line : "auto"` for line and position which seem to work. Not sure if they pass the test though.

**Comment by jsg2021** [comment]
This is not really resolved yet...

**Comment by jsg2021** [comment]
my PR should fix it

**Comment by ChristiaanScheermeijer** [comment]
Oops wrong button!

**Comment by ondrejpar** [comment]
Hi, is there any progress on this? Or maybe a workaround?

**Comment by jsg2021** [comment]
Just waiting for the pr to be merged.

**Comment by Decad** [comment]
We are still getting this issue in Safari 13.0.3 (15608.3.10.1.4). Any news on the PR being merged?

**Comment by gkatsev** [comment]
I believe this is fixed or will soon (in the next release) be fixed in the videojs fork of vtt.js. It's probably the only currently maintained version of vtt.js: https://github.com/videojs/vtt.js (videojs-vtt.js on npm)
